# 🚀 DEPLOY AUTOMÁTICO A GITHUB PAGES
# Workflow optimizado para Carnet Digital UAGro

name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Permisos necesarios para GitHub Pages
permissions:
  contents: write  # Cambiado de read a write para push
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.4'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build for web
      run: flutter build web --release
      
    - name: Copy CNAME file
      run: cp web/CNAME build/web/CNAME
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build/web
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        # Copy build files to root
        cp -r build/web/* .
        
        # Remove temporary index.html if exists
        rm -f index.html.bak
        
        # Configure git with token
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        
        # Add and commit changes
        git add .
        git commit -m "🚀 Auto-deploy Flutter Web App" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}